export const MUNDIAL_COUNTRIES = [
  { name: 'México',              flag: '🇲🇽', iso: 'mx',     host: true  },
  { name: 'Estados Unidos',      flag: '🇺🇸', iso: 'us',     host: true  },
  { name: 'Canadá',              flag: '🇨🇦', iso: 'ca',     host: true  },
  { name: 'Argentina',           flag: '🇦🇷', iso: 'ar' },
  { name: 'Brasil',              flag: '🇧🇷', iso: 'br' },
  { name: 'Uruguay',             flag: '🇺🇾', iso: 'uy' },
  { name: 'Colombia',            flag: '🇨🇴', iso: 'co' },
  { name: 'Ecuador',             flag: '🇪🇨', iso: 'ec' },
  { name: 'Paraguay',            flag: '🇵🇾', iso: 'py' },
  { name: 'Francia',             flag: '🇫🇷', iso: 'fr' },
  { name: 'España',              flag: '🇪🇸', iso: 'es' },
  { name: 'Alemania',            flag: '🇩🇪', iso: 'de' },
  { name: 'Portugal',            flag: '🇵🇹', iso: 'pt' },
  { name: 'Países Bajos',        flag: '🇳🇱', iso: 'nl' },
  { name: 'Inglaterra',          flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', iso: 'gb-eng' },
  { name: 'Croacia',             flag: '🇭🇷', iso: 'hr' },
  { name: 'Bélgica',             flag: '🇧🇪', iso: 'be' },
  { name: 'Suiza',               flag: '🇨🇭', iso: 'ch' },
  { name: 'Austria',             flag: '🇦🇹', iso: 'at' },
  { name: 'Noruega',             flag: '🇳🇴', iso: 'no' },
  { name: 'Suecia',              flag: '🇸🇪', iso: 'se' },
  { name: 'Escocia',             flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', iso: 'gb-sct' },
  { name: 'Turquía',             flag: '🇹🇷', iso: 'tr' },
  { name: 'República Checa',     flag: '🇨🇿', iso: 'cz' },
  { name: 'Bosnia-Herzegovina',  flag: '🇧🇦', iso: 'ba' },
  { name: 'Japón',               flag: '🇯🇵', iso: 'jp' },
  { name: 'Corea del Sur',       flag: '🇰🇷', iso: 'kr' },
  { name: 'Australia',           flag: '🇦🇺', iso: 'au' },
  { name: 'Nueva Zelanda',       flag: '🇳🇿', iso: 'nz' },
  { name: 'Irán',                flag: '🇮🇷', iso: 'ir' },
  { name: 'Arabia Saudí',        flag: '🇸🇦', iso: 'sa' },
  { name: 'Uzbekistán',          flag: '🇺🇿', iso: 'uz' },
  { name: 'Jordania',            flag: '🇯🇴', iso: 'jo' },
  { name: 'Irak',                flag: '🇮🇶', iso: 'iq' },
  { name: 'Catar',               flag: '🇶🇦', iso: 'qa' },
  { name: 'Marruecos',           flag: '🇲🇦', iso: 'ma' },
  { name: 'Túnez',               flag: '🇹🇳', iso: 'tn' },
  { name: 'Egipto',              flag: '🇪🇬', iso: 'eg' },
  { name: 'Argelia',             flag: '🇩🇿', iso: 'dz' },
  { name: 'Ghana',               flag: '🇬🇭', iso: 'gh' },
  { name: 'Senegal',             flag: '🇸🇳', iso: 'sn' },
  { name: 'Costa de Marfil',     flag: '🇨🇮', iso: 'ci' },
  { name: 'Cabo Verde',          flag: '🇨🇻', iso: 'cv' },
  { name: 'Sudáfrica',           flag: '🇿🇦', iso: 'za' },
  { name: 'RD Congo',            flag: '🇨🇩', iso: 'cd' },
  { name: 'Panamá',              flag: '🇵🇦', iso: 'pa' },
  { name: 'Haití',               flag: '🇭🇹', iso: 'ht' },
  { name: 'Curazao',             flag: '🇨🇼', iso: 'cw' },
]

// Pre-built display string: "🇦🇷 Argentina"
export const COUNTRY_OPTIONS = MUNDIAL_COUNTRIES.map((c) => ({
  value: c.name,
  label: `${c.flag} ${c.name}${c.host ? ' ★' : ''}`,
  flag: c.flag,
  host: c.host ?? false,
}))
