"""add match_number to matches

Revision ID: ff9e8dff82e5
Revises: bdb247f203bc
Create Date: 2026-05-29 13:42:27.321223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff9e8dff82e5'
down_revision: Union[str, None] = 'bdb247f203bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_match_number'), 'matches', ['match_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_match_number'), table_name='matches')
    op.drop_column('matches', 'match_number')
    # ### end Alembic commands ###
